### ISSUE TITLE
Go開発に使用するvscode拡張機能を教えて！

### ISSUE THREAD

**Issue by Rin0107** [tetsu-777/rakuraku-reserve-app#18]
vscodeで開発をする上で、以下を実現する拡張機能を教えてほしい！
 - 定義先へジャンプしたい
 - 関数、structにマウスカーソルを合わせたときにgodocが見れるようにしたい
 - debugがしたい

軽く調べてみて使えそうなやつ試して、使えるやつあれば教えて！
これにあまり時間はかけなくて大丈夫！

ついでにこれ全体に共有したいからReadMeにも記載してほしい！

**Comment by kazuoikeda1411** [comment]
取り急ぎ自分でわかってることとして定義先にジャンプするのはcmd(ctrl)+クリックでいけない？
実装の調査するときに使ってるメソッドとかオブジェクトの実装先にいくコマンド。
↑これではない？？

**Comment by kazuoikeda1411** [comment]
上記でできない場合は以下を参照して設定ファイルを修正すればいけそう
[参照](https://kenjimorita.jp/golang-vscode0go-to-definition/)

**Comment by Rin0107** [comment]
> 取り急ぎ自分でわかってることとして定義先にジャンプするのはcmd(ctrl)+クリックでいけない？ 実装の調査するときに使ってるメソッドとかオブジェクトの実装先にいくコマンド。 ↑これではない？？

できんかった！
一番問題なくできそうな、同一ファイル内で定義した変数へのジャンプもできんかった！😥

**Comment by kazuoikeda1411** [comment]
> > 取り急ぎ自分でわかってることとして定義先にジャンプするのはcmd(ctrl)+クリックでいけない？ 実装の調査するときに使ってるメソッドとかオブジェクトの実装先にいくコマンド。 ↑これではない？？
> 
> できんかった！ 一番問題なくできそうな、同一ファイル内で定義した変数へのジャンプもできんかった！😥

以下リンク先にもvscodeの初期設定で入っている感じで書いてあるな、、、F12でもいけない？？
https://gizumo-inc.jp/media/code-reading-shortcut/

**Comment by Rin0107** [comment]
調べてくれてありがとう！
とりあえず

> 定義先へジャンプしたい
関数、structにマウスカーソルを合わせたときにgodocが見れるようにしたい

このあたりは環境構築が原因っぽいから一旦放置でいいや...
debugは他の人が知らんかったらとりあえずプリントデバッグでいいや...

>
